# Generated by Django 3.1.2 on 2020-10-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajos',
            name='cargo',
        ),
        migrations.AddField(
            model_name='trabajos',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trabajos',
            name='paga',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
